hl.on("hyprland.start",function()
    hl.exec_cmd("$HOME/.local/bin/hypr-win8-session-start")
    hl.exec_cmd("hypridle -c $HOME/.config/hypr/win8/hypridle.conf")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("easyeffects --hide-window --service-mode")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("pidof hyprsunset || hyprsunset")
end)
